/*LOT3_APPLI_Jallais_Adrien-test.sql*/


SELECT * FROM COMPTE WHERE IdCompte = 2;
SELECT * FROM OPERATION WHERE IdCompte = 2;

EXECUTE PACK_APP_BANQUE.AJOUTNOUVOPERATION(2, 1234);

SELECT * FROM COMPTE WHERE IdCompte = 2;
SELECT * FROM OPERATION WHERE IdCompte = 2;
SELECT * FROM AUDITDECOUVERT WHERE IdCompte = 2 ;

EXECUTE PACK_APP_BANQUE.AJOUTNOUVOPERATION(2, -12345);

SELECT * FROM COMPTE WHERE IdCompte = 2;
SELECT * FROM OPERATION WHERE IdCompte = 2;
SELECT * FROM AUDITDECOUVERT WHERE IdCompte = 2 ;

EXECUTE PACK_APP_BANQUE.AJOUTNOUVOPERATION(2, -12);

SELECT * FROM COMPTE WHERE IdCompte = 2;
SELECT * FROM OPERATION WHERE IdCompte = 2;
SELECT * FROM AUDITDECOUVERT WHERE IdCompte = 2 ;

EXECUTE PACK_APP_BANQUE.AJOUTNOUVOPERATION(2, 12+12345);

SELECT * FROM COMPTE WHERE IdCompte = 2;
SELECT * FROM OPERATION WHERE IdCompte = 2;
SELECT * FROM AUDITDECOUVERT WHERE IdCompte = 2 ;


