/*LOT1_APPLI_Jallais_Adrien-1.txt*/

/*BANQUE*/

CREATE TABLE BANQUE(
	IdBanque INTEGER,
	LibelleBanque VARCHAR(50) CONSTRAINT NN_LibelleBanque NOT NULL,
	CPBanque CHAR(5) CONSTRAINT NN_CPBanque NOT NULL,
	AdresseBanque VARCHAR(50) CONSTRAINT NN_AdresseBanque NOT NULL,
	VilleBanque VARCHAR(30) CONSTRAINT NN_VilleBanque NOT NULL
);

ALTER TABLE BANQUE ADD CONSTRAINT PK_IdBanque PRIMARY KEY (IdBanque) ;
ALTER TABLE BANQUE ADD CONSTRAINT U_LibelleBanque UNIQUE (LibelleBanque) ;

CREATE SEQUENCE SeqIdBanque
	START WITH     1
	INCREMENT BY   1
	NOCACHE
	NOCYCLE ;
	

/*TYPECOMPTE*/

CREATE TABLE TYPECOMPTE(
	IdTypeCompte INTEGER,
	LibelleTypeCompte VARCHAR(30) CONSTRAINT NN_LibelleTypeCompte NOT NULL 
);

ALTER TABLE TYPECOMPTE ADD CONSTRAINT PK_IdTypeCompte PRIMARY KEY (IdTypeCompte) ;

CREATE SEQUENCE SeqIdTypeCompte
	START WITH     1
	INCREMENT BY   1
	NOCACHE
	NOCYCLE ;


/*OPERATION*/

CREATE TABLE OPERATION(
	IdOperation INTEGER,
	DateOperation DATE CONSTRAINT NN_DateOperation NOT NULL,
	MontantOperation NUMBER(10,2) CONSTRAINT NN_MontantOperation NOT NULL
);

ALTER TABLE OPERATION ADD CONSTRAINT PK_IdOperation PRIMARY KEY (IdOperation) ;
ALTER TABLE OPERATION MODIFY DateOperation DEFAULT sysdate ; 
/*ALTER TABLE OPERATION ADD CONSTRAINT DK_DateOperation DEFAULT 'SYSDATE' FOR DateOperation ;*/

CREATE SEQUENCE SeqIdOperation
	START WITH     1
	INCREMENT BY   1
	NOCACHE
	NOCYCLE ;


/*COMPTE*/

CREATE TABLE COMPTE(
	IdCompte INTEGER,
	LibelleCompte VARCHAR(30) CONSTRAINT NN_LibelleCompte NOT NULL, 
	SoldeCompte NUMBER(10,2) CONSTRAINT NN_SoldeCompte NOT NULL, 
	DecouvertAutorise NUMBER(10,2)  CONSTRAINT NN_DecouvertAutorise NOT NULL, 
	DateOuvertureCompte DATE CONSTRAINT NN_DateOuvertureCompte NOT NULL
);

ALTER TABLE COMPTE ADD CONSTRAINT PK_IdCompte PRIMARY KEY (IdCompte) ;
ALTER TABLE COMPTE ADD CONSTRAINT U_LibelleCompte UNIQUE (LibelleCompte) ;
ALTER TABLE COMPTE MODIFY SoldeCompte DEFAULT 0.00 ; 
/*ALTER TABLE COMPTE ADD CONSTRAINT DK_SoldeCompte DEFAULT '0' FOR SoldeCompte ;*/
ALTER TABLE COMPTE MODIFY DecouvertAutorise DEFAULT 0.00 ; 
/*ALTER TABLE COMPTE ADD CONSTRAINT DK_DecouvertAutorise DEFAULT '0' FOR DecouvertAutorise ;*/
ALTER TABLE COMPTE ADD CONSTRAINT CK_C_DecouvertAutorise CHECK(DecouvertAutorise>=0) ;
ALTER TABLE COMPTE MODIFY DateOuvertureCompte DEFAULT sysdate ;  
/*ALTER TABLE COMPTE ADD CONSTRAINT DK_DateOuvertureCompte DEFAULT 'SYSDATE' FOR DateOuvertureCompte ;*/

CREATE SEQUENCE SeqIdCompte
	START WITH     1
	INCREMENT BY   1
	NOCACHE
	NOCYCLE ;
	

/*AUDITDECOUVERT*/

CREATE TABLE AUDITDECOUVERT(
	IdAudit INTEGER,
	IdCompte INTEGER CONSTRAINT NN_A_IdCompte NOT NULL,
	LibelleCompte VARCHAR(30) CONSTRAINT NN_A_LibelleCompte NOT NULL,
	SoldeCompte NUMBER(10,2) CONSTRAINT NN_A_SoldeCompte NOT NULL,
	DecouvertAutorise NUMBER(10,2) CONSTRAINT NN_A_DecouvertAutorise NOT NULL,
	Depassement NUMBER(10,2) CONSTRAINT NN_A_Depassement NOT NULL,
	IdDerniereOperation INTEGER CONSTRAINT NN_A_IdDerniereOperation NOT NULL
);

ALTER TABLE AUDITDECOUVERT ADD CONSTRAINT PK_A_IdAudit PRIMARY KEY (IdAudit) ;
ALTER TABLE AUDITDECOUVERT ADD CONSTRAINT CK_A_DecouvertAutorise CHECK(DecouvertAutorise>=0) ;
ALTER TABLE AUDITDECOUVERT MODIFY SoldeCompte DEFAULT 0.00 ; 
/*ALTER TABLE AUDITDECOUVERT ADD CONSTRAINT DK_SOLDECOMPTE DEFAULT 0.00 FOR SOLDECOMPTE ;*/

CREATE SEQUENCE SeqIdAudit
	START WITH     1
	INCREMENT BY   1
	NOCACHE
	NOCYCLE ;




/*association COMPTE BANQUE*/
ALTER TABLE COMPTE ADD (
    IdBanque INTEGER CONSTRAINT NN_IdBanque NOT NULL
);
ALTER TABLE COMPTE ADD CONSTRAINT FK_IdBanque FOREIGN KEY(IdBanque) REFERENCES BANQUE(IdBanque) ;


/*association COMPTE TYPECOMPTE*/
ALTER TABLE COMPTE ADD (
    IdTypeCompte INTEGER CONSTRAINT NN_IdTypeCompte NOT NULL
);
ALTER TABLE COMPTE ADD CONSTRAINT FK_IdTypeCompte FOREIGN KEY(IdTypeCompte) REFERENCES TYPECOMPTE(IdTypeCompte) ;


/*association OPERATION COMPTE*/
ALTER TABLE OPERATION ADD (
    IdCompte INTEGER CONSTRAINT NN_IdCompte NOT NULL
);
ALTER TABLE OPERATION ADD CONSTRAINT FK_IdCompte FOREIGN KEY(IdCompte) REFERENCES COMPTE(IdCompte) ;


